# Generated by Django 3.2.5 on 2021-08-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex07', '0003_alter_movies_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
